groups:
  - name: a
    jobs:
      - ahello-world
  - name: b
    jobs:
      - bhello-world
resource_types:
  - name: busyimage
    type: docker-image
    source:
      repository: busybox
resources:
  - name: mock
    type: mock-resource
jobs:
  - name: ahello-world
    plan:
      - task: say-bhello
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: busybox
          run:
            path: echo
            args:
              - '--version'
  - name: bhello-world
    plan:
      - task: say-bhello
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: busybox
          run:
            path: echo
            args:
              - '--version'
