---
task-config: &task-config
  platform: linux
  image_resource:
    type: registry-image
    source: { repository: busybox }

var_sources:
- name: dumb
  type: dummy
  config:
    vars:
      simple: hello!
      user:
        username: big
        password: sekrit
    env-vars:
      SOME_SIMPLE_VAR: simple-var
      SOME_LONG_VAR: |
        This is an example of using YAML multi-line string syntax to set a very
        long environment variable value.
      SOME_NUMERIC_VALUE: "1"

resources:
- name: concourse-examples
  type: git
  icon: github
  source:
    uri: https://github.com/ibrezm1/concourse-test-01.git
    branch: main

jobs:
- name: read-the-readme
  plan:
  - get: concourse-examples
    trigger: true
  - task: cat-readme
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: python
      inputs: # pass concourse-examples into this task step
      - name: concourse-examples
      run:
        path: sh
        args:
        - -exc
        - |
          echo simple: ((dumb:simple)) 
          echo username: ((dumb:user.username))
          whoami
          cat concourse-examples/Readme.md
          find .
          python concourse-examples/01-pipe-git/python-version.py
          pwd
          env
    on_success:
      task: task-success
      config:
        << : *task-config
        run:
          path: echo
          args: ["This task succeeded!"]
    on_failure:
      task: task-failure
      config:
        << : *task-config
        run:
          path: echo
          args: ["This task failed!"]
  on_success:
    task: job-success
    config:
      << : *task-config
      run:
        path: echo
        args: ["This job succeeded!"]
  on_failure:
    task: job-failure
    config:
      << : *task-config
      run:
        path: echo
        args: ["This job failed!"]