---
# fly -t tutorial set-pipeline -p pipeline-res -c 01-pipe-git/pipe-in-git.yml 
groups:
- name: dev
  jobs: [dread-the-readme, dread-the-breadme]
- name: stg
  jobs: [sread-the-readme, sread-the-breadme]


task-config: &task-config
  platform: linux
  image_resource:
    type: registry-image
    source: { repository: busybox }

var_sources:
- name: dumb
  type: dummy
  config:
    vars:
      simple: hello!
      user:
        username: big
        password: sekrit


resources:
- name: concourse-examples
  type: git
  icon: github
  source:
    uri: https://github.com/ibrezm1/concourse-test-01.git
    branch: main

jobs:
- name: dread-the-readme
  plan:
  - get: concourse-examples
    trigger: false
  - task: cat-readme
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox  # change to python
      inputs: # pass concourse-examples into this task step
      - name: concourse-examples
      run:
        path: sh
        # python concourse-examples/01-pipe-git/python-version.py
        args:
        - -exc
        - |
          echo simple: ((dumb:simple)) 
          echo username: ((dumb:user.username))
          whoami
          cat concourse-examples/Readme.md  
          find .
          pwd
          env

- name: dread-the-breadme
  plan:
  - get: concourse-examples
    trigger: false
  - task: bat-readme
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox  # change to python
      inputs: # pass concourse-examples into this task step
      - name: concourse-examples
      run:
        path: sh
        # python concourse-examples/01-pipe-git/python-version.py
        args:
        - -exc
        - |
          whoami
    on_success:
      task: task-success
      config:
        << : *task-config
        run:
          path: echo
          args: ["This task succeeded!"]
    on_failure:
      task: task-failure
      config:
        << : *task-config
        run:
          path: echo
          args: ["This task failed!"]
  on_success:
    task: job-success
    config:
      << : *task-config
      run:
        path: echo
        args: ["This job succeeded!"]
  on_failure:
    task: job-failure
    config:
      << : *task-config
      run:
        path: echo
        args: ["This job failed!"]

- name: sread-the-readme
  plan:
  - get: concourse-examples
    trigger: false
  - task: cat-readme
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox  # change to python
      inputs: # pass concourse-examples into this task step
      - name: concourse-examples
      run:
        path: sh
        # python concourse-examples/01-pipe-git/python-version.py
        args:
        - -exc
        - |
          echo simple: ((dumb:simple)) 
          echo username: ((dumb:user.username))
          whoami
          cat concourse-examples/Readme.md  
          find .
          pwd
          env

- name: sread-the-breadme
  plan:
  - get: concourse-examples
    trigger: false
  - task: bat-readme
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox  # change to python
      inputs: # pass concourse-examples into this task step
      - name: concourse-examples
      run:
        path: sh
        # python concourse-examples/01-pipe-git/python-version.py
        args:
        - -exc
        - |
          whoami
    on_success:
      task: task-success
      config:
        << : *task-config
        run:
          path: echo
          args: ["This task succeeded!"]
    on_failure:
      task: task-failure
      config:
        << : *task-config
        run:
          path: echo
          args: ["This task failed!"]
  on_success:
    task: job-success
    config:
      << : *task-config
      run:
        path: echo
        args: ["This job succeeded!"]
  on_failure:
    task: job-failure
    config:
      << : *task-config
      run:
        path: echo
        args: ["This job failed!"]


